spring:
  .datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 9511040801
  .jpa:
    .hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      current_session_context_class: thread
      ddl-auto: update

server:
  port: 9000

jwt:
  .secret:
    .access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==