version: '3'

services:
  mysql:
    image: 'mysql:8.0.26'
    ports:
      - '3306:3306'
    environment:
      MYSQL_PASSWORD: '9511040801'
      MYSQL_USER: 'root'
      MYSQL_DB: 'test'

  app:
    ports:
      - '5555:5555'